### ISSUE TITLE
nocs/notes.md missing

### ISSUE THREAD

**Issue by PierreCorell** [rosell-dk/exec-with-fallback#15]
Hi @rosell-dk,

I am using the Wordpress webp-express plugin, which includes this repository. 
Since version 0.25.1 the wp-cli file sum check is failing because of a missing file, which results in a failing automated deploy script.

```
$ which wp
/usr/local/bin/wp
$ wp plugin verify-checksums webp-express 
+--------------+---------------------------------------------------+-----------------+
| plugin_name  | file                                              | message         |
+--------------+---------------------------------------------------+-----------------+
| webp-express | vendor/rosell-dk/exec-with-fallback/docs/notes.md | File is missing |
+--------------+---------------------------------------------------+-----------------+
Error: No plugins verified (1 failed).
```

Could you add the missing file again or update the webp-express plugin accordingly, please?

**Comment by rosell-dk** [comment]
The file was removed because it contained a code example that triggered a firewall, as reported [here](https://github.com/rosell-dk/webp-convert/issues/325). The file was just notes and code examples found on the internet, so I removed it completely.

I will update the webp-express plugin
